### ISSUE TITLE
[Bug] Problems interacting with the ProjectE transmutation table

### ISSUE THREAD

**Issue by FnordMan** [orbwoi/UniversalRemote#12]
One of two things happens: 
1: It won't let you pull anything out
2: you'll get ghost items in your inventory

Not a really huge issue as i've already got a nice workaround in place in the form of a miniature Refined Storage system in place as the remote works great with the crafting grid.

**Comment by orbwoi** [comment]
Fixed in 1.12-0.9.5! :)
