### ISSUE TITLE
0.9.5 breaks Good Ol' Currency GUI

### ISSUE THREAD

**Issue by D3nnis3n** [orbwoi/UniversalRemote#15]
See this https://ibb.co/hrmdAb
The Infinite sign should be clickable and have a purple background like the other buttons. Both is no longer possible as long as your mod is installed.

**Comment by orbwoi** [comment]
And this is just when used normally not through a remote?

**Comment by D3nnis3n** [comment]
Yes. I did not try using a remote on it. I got the Dev of the mod on discord and i wanted to test his mod, but then this issue arose and we pretty fast found out it was yours causing this.

**Comment by orbwoi** [comment]
Can I talk to him on discord? He is probably using anti-fake player code like ic2 does. I had to add a special exception for ic2.

**Comment by BeardlessBrady** [comment]
For that specific tab all I'm doing is checking if the player opening the gui is in creative mode or not

**Comment by orbwoi** [comment]
Hmmm.. it seems to be working for me: https://ibb.co/cTUC3w

**Comment by D3nnis3n** [comment]
Well, all i can say is it ceased working as soon as i installed your mod, and went back to working when i removed it. Same with the skins.

I use forge 1512, btw.

**Comment by D3nnis3n** [comment]
And yeh, i indeed was in creative mod.

**Comment by orbwoi** [comment]
I was in creative mod and using forge 1.12.2-14.23.0.2512 when I took that screenie.

**Comment by D3nnis3n** [comment]
Lawl.

**Comment by D3nnis3n** [comment]
I do test on server only.

**Comment by D3nnis3n** [comment]
I'll throw up a singleplayer instance to look it up.

**Comment by orbwoi** [comment]
Let me test on server... Still working for me. https://ibb.co/b6yrVb
What version are you testing? I built off the head of master for the currency mod.

**Comment by D3nnis3n** [comment]
Currency 1.12-1.2.6 BETA

**Comment by D3nnis3n** [comment]
Confirmed to work in SSP. But not on SMP.

**Comment by orbwoi** [comment]
Working in both for me. See second screenshot above for server test.

**Comment by D3nnis3n** [comment]
All clear with only your mod.

**Comment by D3nnis3n** [comment]
Despite server-side.

**Comment by D3nnis3n** [comment]
I'd say it works every second server start. But on every start you shortly see the Alex skin, then it changes to the real skin. As for the currency gui it also works only on every second server restart. Seems it will be a "not reproducable".

**Comment by D3nnis3n** [comment]
WTF.

**Comment by D3nnis3n** [comment]
So, if you didn't understand my poor writing: Out of starting the server ten times, 5 times the bug was present, 5 times it wasn't. I can't tell you why. This happens with and without other mods, as long as your mod is active.

**Comment by orbwoi** [comment]
For one or both bugs? It isn't clear which one you are talking about.

**Comment by D3nnis3n** [comment]
For both bugs.

For Alex: When your mod is installed on both SSP and SMP i shortly see alex, then it switches to my real skin. But on SSP it only does that in 50% of 10 Server Starts. In the other 50% i'm alex for the whole time.
When your mod is not installed, i never see alex but ever my skin from the beginning. There is no difference if other mods are installed. (I ever have optifine, otherwise i can't play)

For Currency: It works on SSP in every case. On SMP the bug is present in 50% of the server starts. It's just random. I start the server: It works. I restart it: It doesn't. There is no difference if other mods are installed. (I ever have optifine, otherwise i can't play)

Maybe some internet files can'T be downloaded or something like that!?

**Comment by orbwoi** [comment]
Alex: This is most likely related to optifine. I do not test with optifine nor do I plan to do so. Installing that is a guaranteed risk of some visual glitches.
Currency: Are you saying you see that bug 50% of the time with ONLY currency installed (e.g. remote is not installed)?

**Comment by D3nnis3n** [comment]
I'll keep the mod on my PTR and see what comes up tomorrow when all the others play again.

**Comment by D3nnis3n** [comment]
Currency: Are you saying you see that bug 50% of the time with ONLY currency installed (e.g. remote is not installed)? No. Your Mod must be installed, too.

> Alex: This is most likely related to optifine. I do not test with optifine nor do I plan to do so. Installing that is a guaranteed risk of some visual glitches.
This does not happen without your mod and some of us are forced to use Optifine as it's the only mod allowing you to downscale resolution. E.g. i got a 4K monitor, but minecraft being the only game that my graphics card can not power in that resolution makes it not playable for me otherwise.

**Comment by orbwoi** [comment]
I may close these bugs for now until we get some more data. I cannot reproduce the error on my machine. You should open a new bug if you find better way to reproduce it especially without optfine installed. Also, let me know if those other players see similar issues.

**Comment by D3nnis3n** [comment]
I'll report back.

**Comment by orbwoi** [comment]
Note from later: appears to be fixed in 0.9.6

**Comment by BeardlessBrady** [comment]
How did you fix it?

**Comment by orbwoi** [comment]
It appears there was a race condition where MinecraftProxy could sometimes leak into Minecraft.player.mc. That proxy version also wasn't populated with the client player's full data. Now both are fixed.
