### ISSUE TITLE
0.9.6 is incompatible with SpongeForge

### ISSUE THREAD

**Issue by D3nnis3n** [orbwoi/UniversalRemote#16]
When SpongeForge is installed, Clients get a Internal Server Error when trying to join. This is what isee in the console:

> [19:36:20] [Netty Epoll Server IO #1/INFO] [neid]: Patching class: "net.minecraft.network.play.server.SPacketBlockAction" with Transformer Group: "TransformerGroupBlockHardcoredConstants"
> [19:36:23] [User Authenticator #1/INFO]: UUID of player D3nnis3n is 4995603c-ad89-46a1-b858-c8b3e8ba863d
> [19:36:23] [Server thread/WARN] [Sponge]: No entity type is registered for class clayborn.universalremote.hooks.entity.HookedEntityPlayerMP
> [19:36:23] [Netty Epoll Server IO #2/INFO] [FML]: Client protocol version 2
> [19:36:23] [Netty Epoll Server IO #2/INFO] [FML]: Client attempting to join with 171 mods : levelup2@${version},blockdrops@1.3.0,disenchanter@1.5,questbook@3.0.0-1.12.1,binniecore@unspecified,unicodefontextensioncore@1.12.2-2.3,upsizer@4.0,compot@1.1,rftools@7.12,animania@1.3.5,additionalbanners@1.1.40,multistorage@1.4.4,thespotlightmod@1.2.0.98,cofhcore@4.3.6,malisisswitches@1.12-5.0.0,multimine@1.5.7,craftstudioapi@1.0.0,modnametooltip@1.10.0,forgeendertech@1.12.2-4.1.0.0,reborncore@3.4.8.138,jeibees@0.9.0.5,betterquesting@2.5.236,xnet@1.4.1,neid@1.5.4.2,weather2@1.12.1-2.5.5-a,forgelin@1.5.1,reconstructor@2.11a,malisisblocks@1.12-6.0.2,cofhworld@1.0.1,modcurrency@1.12-1.2.6,mekanismgenerators@9.4.1,carryon@1.6.1,jeresources@0.8.5.26,mcmultipart@2.3.3,bq_standard@2.4.134,fbp@2.2.2,shetiphiancore@3.5.0.2,wts@1.1.0,vbe@GRADLE:VERSION-GRADLE:BUILD,malisisdoors@1.12.2-7.1.1,felling@1.2.3,architecturecraft@@VERSION@,refinedstorage@1.5.21,storagedrawersextra@@VERSION@,immersivetech@1.3.4,wificharge@1.3.0,storageboats@1.6,extratrees@2.4.0.82,industrialforegoing@1.12.1-1.12.1,malisiscore@1.12.2-6.1.7,rebornstorage@1.0.0,tinkertoolleveling@1.12-1.0.2b.DEV.1a79301,unidict@1.12.1-1.0,crafttweakerjei@2.0.0,jehc@1.3.1,mtlib@@VERSION@,botany@2.4.0.82,redstoneflux@2.0.1,soulshardstow@1.12-2.7.3-52,advancedrocketry@1.2.3.-6,modtweaker@4.0.3,gendustry@1.6.5.5,densemetals@1.0.1,fairylights@2.1.1,teslacorelib_registries@1.0.9,watercontrolextreme@1.0.0,jepb@1.2.1,modernmetals@2.5.0-beta2,topaddons@1.12.2-1.1.1,teslacorelib@1.0.9,rftoolscontrol@1.6.8,sanlib@1.2.0,nethermetals@1.2.0-beta1,FML@8.0.99.99,tombstone@1.3.8,simplyconveyors@3.0.6,customnpcs@1.12,worldedit@6.1.8,mekanismtools@9.4.1,libvulpes@0.2.6.-5,bigreactors@1.12-0.4.5.40,adchimneys@1.12.2-3.1.0.0,presets@3.4.7.2,instantunify@1.0.5,vtt@0.6.4,fastleafdecay@v14,codechickenlib@3.1.3.313,corail_pillar@4.0.0,binniedesign@1.0,unicodefontextension@1.12.2-2.3,ctgui@1.0.0,extendedrenderer@v1.0,inventoryspam@1.0.2,supersoundmuffler@1.0.2.9,configmod@v1.0,jei@4.8.0.109,basemetals@2.5.0-beta2,endmetals@1.2.0-beta1,nei@${mod_version},bibliocraft@2.4.3,scannable@1.6.2.13,mekanism@9.4.1,bdlib@1.14.3.10,opencomputers@1.7.0.20,redstonepaste@1.7.5,waystones@4.0.17,mcp@9.42,sanplayermodel@1.0.0,nuclearcraft@2.5a,csb_ench_table@1.1.2,chameleon@1.12-4.1.3,vials@1.2.1.1,harvestcraft@1.12.2a,mw@1.12.2,extrabees@2.4.0.82,crafttweaker@4.0.8,endercompass@1.2.6.1,forge@14.23.0.2512,dsurround@3.4.7.2,cyclicmagic@1.9.5,infernalmobs@1.7.3,ironchest@1.12.2-7.0.34.820,craftingtweaks@8.1.6,zerocore@1.12-0.1.1.0,minecraft@1.12.2,tconstruct@1.12-2.7.4.34,claysoldiers@3.0.0-alpha.4.1,theoneprobe@1.4.18,roughtweaks@1.0,toolbelt@1.7.1,immersiveengineering@0.12-74,applecore@2.2.2,universalremote@1.12-0.9.6,stevescarts@${version},chickenchunks@2.4.0.70,genetics@2.4.0.82,betterfonts@1.9.1,harvesttweaks@1.12-0.1.5.DEV.86c8a67,signpic@2.8.1,car@1.2.9,jeiintegration@1.5.1.36,mantle@1.12-1.3.1.21,loottweaker@0.0.6.3,worldutils@0.4.2,advancedrocketrycore@1,keywizard@1.10.2-1.5,betterplacement@1.0.0-1,storagedrawers@1.12-5.2.5,corail_pillar_extension_forestry@4.0.0,tinker_io@release 2.5.5e,worldeditcuife2@2.1.2-mf-1.12.2-14.23.0.2487,coroutil@1.12.1-1.1.20,minecolonies@1.12.2-0.8.4280,wanionlib@1.12.1-1.0,appleskin@1.0.8,recipehandler@0.9,flatcoloredblocks@mc1.12-6.6,foamfix@0.8.0-1.12,opencomputers|core@1.7.0.20,spiceoflife@1.3.11,trade@1.0.2,baseminerals@2.5.0-beta2,refinedstorageaddons@0.2,minemenu@1.6.2,soundfilters@0.10_for_1.12,chiselsandbits@14.8,modernlamps@1.0.3,thuttech@6.0.6,thutcore@5.11.5,betterfoliage@2.1.10,forestry@5.6.0.201
> [19:36:23] [Netty Epoll Server IO #2/INFO] [FML]: Attempting connection with missing mods [spongeapi, sponge, dynmap, nucleus, pieconomy] at CLIENT
> [19:36:29] [Server thread/INFO] [FML]: [Server thread] Server side modded connection established
> [19:36:29] [Server thread/WARN]: Failed to handle packet for /178.27.85.65:61068
> net.minecraft.util.ReportedException: Sending packet
>         at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:891) ~[pa.class:?]
>         at net.minecraft.server.management.PlayerList.handler$playerLoggedIn2$zim000(PlayerList.java:2011) ~[pl.class:?]
>         at net.minecraft.server.management.PlayerList.func_72377_c(PlayerList.java:367) ~[pl.class:?]
>         at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1567) ~[pl.class:?]
>         at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) ~[NetworkDispatcher.class:?]
>         at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
>         at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
>         at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
>         at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) [oz.class:?]
>         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
>         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
> Caused by: java.lang.NullPointerException
>         at org.spongepowered.common.entity.player.tab.SpongeTabList.sendUpdate(SpongeTabList.java:190) ~[SpongeTabList.class:1.12.2-2503-7.0.0-BETA-2706]
>         at org.spongepowered.common.entity.player.tab.SpongeTabList.addEntry(SpongeTabList.java:161) ~[SpongeTabList.class:1.12.2-2503-7.0.0-BETA-2706]
>         at org.spongepowered.common.entity.player.tab.SpongeTabList.addEntry(SpongeTabList.java:141) ~[SpongeTabList.class:1.12.2-2503-7.0.0-BETA-2706]
>         at org.spongepowered.common.entity.player.tab.SpongeTabList.updateEntriesOnSend(SpongeTabList.java:205) ~[SpongeTabList.class:1.12.2-2503-7.0.0-BETA-2706]
>         at net.minecraft.network.NetHandlerPlayServer.rewritePacket(NetHandlerPlayServer.java:2560) ~[pa.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.redirect$onSendPacket$zia000(NetHandlerPlayServer.java:2540) ~[pa.class:?]
>         at net.minecraft.network.NetHandlerPlayServer.func_147359_a(NetHandlerPlayServer.java:878) ~[pa.class:?]
>         ... 13 more
> [19:36:29] [Server thread/INFO]: D3nnis3n lost connection: Internal server error
> [19:36:29] [Server thread/INFO]: D3nnis3n left the game

**Comment by orbwoi** [comment]
Hmmm... it seems SpongeForge can't handle the extended player class. Sad.

I'll need to come up with a compatibility patch. At this point I'm starting to wonder if writing a CoreMod for the hooks would be less prone to arcane errors...

**Comment by orbwoi** [comment]
What 1.12.2 spongeforge are you using? All the ones on the website and GitHub repro seem to crash on startup for me.

**Comment by D3nnis3n** [comment]
2706. Please note Sponge is for Servers only. It will not work on Clients,
its like Bukkit was and provides the possibility to use Plugins like Towny.

Am 23.10.2017 03:58 schrieb "Clayborn" <notifications@github.com>:

**Comment by D3nnis3n** [comment]
I tried 0.9.7 – the issue persists.

Gesendet von Mail für Windows 10

Von: Clayborn
Gesendet: Montag, 23. Oktober 2017 03:58
An: orbwoi/UniversalRemote
Cc: D3nnis3n; Author
Betreff: Re: [orbwoi/UniversalRemote] 0.9.6 is incompatible with SpongeForge(#16)

What 1.12.2 spongeforge are you using? All the ones on the website and GitHub repro seem to crash on startup for me.

**Comment by orbwoi** [comment]
No it was the dedicated server that wouldn't start. I have used sponge on my own servers before. I will look futher into this when I can.

**Comment by D3nnis3n** [comment]
Well, then im Sorry, my server Starts fine, though.

Am 24.10.2017 00:57 schrieb "Clayborn" <notifications@github.com>:

No it was the dedicated server that wouldn't start. I have used sponge on
my own servers before. I will look futher into this when I can.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/orbwoi/UniversalRemote/issues/16#issuecomment-338820556>,
or mute the thread

**Comment by orbwoi** [comment]
I believe you. It may be because of the debugger. If that is the case it will be very painful to try and fix. I definately want the mod to work with sponge if possible.

**Comment by orbwoi** [comment]
Reported fixed by D3nnis3n in 0.9.8! :)
