### ISSUE TITLE
issue with 0.9.6 and combat

### ISSUE THREAD

**Issue by cwdean** [orbwoi/UniversalRemote#18]
There appears to be a problem with UniversalRemote-1.12.2-0.9.6.jar and combat.  When attempting to kill any mob I get an server error:
Ticking entityjava.lang.NullPointerException: Ticking entity
	at net.minecraft.entity.player.EntityPlayerMP.func_152111_bt(EntityPlayerMP.java:295)
	at net.minecraft.util.CombatTracker.func_94547_a(SourceFile:65)
	at net.minecraft.entity.player.EntityPlayer.func_70665_d(EntityPlayer.java:1132)
etc.

and Minecraft aborts.  When I disable UniversalRemote Minecraft works fine again.  I thought it might be a compability issue with ClassicCombat but I disabled that mod and tried fighting.  Unfortunately the error still occurs...so it appears to be an explicit problem just with UniversalRemote and general MC combat.  Hope this is helpful and that this can be easily fixed.

**Comment by orbwoi** [comment]
I will look into this. There was a behind the scenes change in 0.9.6 for players which caused a few issues. Look for a fix release soon.

**Comment by orbwoi** [comment]
Fixed in 0.9.7.
