### ISSUE TITLE
Binding to a void dimension block... is a bad idea

### ISSUE THREAD

**Issue by prozacgod** [orbwoi/UniversalRemote#22]
https://minecraft.curseforge.com/projects/simple-void-world

When you bind it to the void world block from the above mod... and then you use the void dimension block... you become simultaneously in both worlds.  You can only interact with the void world, but you are still physically in the Overworld!   (You can see the void dimension, but the overworld physics seems to have you colliding in the overworld)

Hilarious bug!! 10/10 Best mod ;)

**Comment by prozacgod** [comment]
Okay it gets weirder, I'm wondering how you triggered the remote, like there may be some trickery involved.  

As I was fiddling around, I found that I could right click existing blocks and the block in the overworld would magically appear, eventually I made my way back to the original void block and clicked it.  I got jostled around like I was tp'd to the void and then this time I could interact with blocks but there were phantom leftovers from when I was "psuedo here"

Eventually I found the void's own void block and was able to get back home.

Seems like at least you can do some crazy complicated near impossible thing to fix it.

(Wonder what this looks like in multiplayer? )

**Comment by orbwoi** [comment]
That sounds a like a client/server world de-sync. That shouldn't be happening.
I haven't had issues with other teleporters (RFTools, Mining World).

And yes, plenty of trickery is involved to make the remotes work. It may seem like simple, but behind the scenes there is a lot of code and complication to add a simple function.

Let me take a quick look at this...

**Comment by orbwoi** [comment]
So much for quick. That was a huge pain to fix. xD

You should have better luck in 0.9.10!
