### ISSUE TITLE
[Feature] Please add a way to remove power useage requirement (config?)

### ISSUE THREAD

**Issue by PrinceOfAmber** [orbwoi/UniversalRemote#5]
I dont have any power generation systems in my modpack, and I really want to use this remote.  

I could not find a config file when I looked, is there any way to just toggle off the power consumption? So even if it has zero remaining it still works?

Or you could add a creative-only mode version if that is easier

**Comment by orbwoi** [comment]
Yes, both those things are planned.

0.9.0 will have config file including the option to disable power. That might be a little OP though...

Later on maybe there should be option to power it by consuming redstone or enderpearls?

The 0.8.X series is about compatability and bug fixes to the remote functionality itself.

After that comes config, upgrades, and the multislot advanced remote.

**Comment by orbwoi** [comment]
Config file with required options added in 0.9.0 which was just released. Closing feature request.
