### ISSUE TITLE
AE2 Terminal Issues

### ISSUE THREAD

**Issue by Cal26lum** [orbwoi/UniversalRemote#6]
While it is possible to bind to an AE2 terminal, you cannot access any items stored on the system. This is unusual, as it was possible in previous versions - even 0.8.3.

Versions:
Universal Remote 0.9.0
Minecraft 1.12.1
Forge 14.22.0.2463
Applied Energistics 2 rv5-alpha-3

**Comment by orbwoi** [comment]
Well shucks...

To make the config work as well as improve general compatibility, I had to make a bunch of behind the scenes changes in 0.9.0. That's why it was a major release. A few things broke from that but I thought I had fixed them all before release.

I'll make a hotfix release for this.

**Comment by orbwoi** [comment]
Okay, easy fix- try again in 0.9.1!
