### ISSUE TITLE
Spanish Translation ^_^

### ISSUE THREAD

**Issue by Lightone** [orbwoi/UniversalRemote#7]
Thanks for your great work :D i give  a help with the translations in spanish 

item.universalremote.item_universal_remote.name=Mando universal
universalremote.strings.unbound=Sin vincular
universalremote.strings.notbounderror=!El mando universal no está vinculado a ningun bloque!
universalremote.strings.boundnotloaded=El vínculo del mando universal no ha sido cargado!
universalremote.strings.showmore=Mante presionado la tecla shift para ver las instrucciones
universalremote.strings.instructionsOne=Presiona la tecla shift mas click derecho para vincular a un bloque
universalremote.strings.instructionsTwo=Click en el aire para activar el bloque vinculado
itemGroup.universalremotetab=Mando universal
universalremote.strings.notenoughpower=El mando universal no tiene poder!
universalremote.strings.bound=El mando universal se ha vinculado a un bloque.
universalremote.strings.blockchanged=El vínculo de bloque ha sido remplazado y necesita ser re vinculado 
universalremote.strings.powertooltip=%s/%s Energía
universalremote.strings.crossdimerror=El vínculo del bloque esta en otra dimensión 
universalremote.version.update_available=Versión %s ya está disponible
universalremote.version.download=Descargar
universalremote.version.click_to_download=Click para descargar
universalremote.strings.configtitle=Configuración del mando universal
universalremote.strings.blockblacklist=El bloque objetivo está en lista negra

Translations By Guartinajo 
`

**Comment by orbwoi** [comment]
Added in 0.9.2, thanks!
