### ISSUE TITLE
Strange behavior when vinculate the remote with backpack (UniversalRemote-1.12-0.9.1)

### ISSUE THREAD

**Issue by Lightone** [orbwoi/UniversalRemote#8]
when you do that the game lost the interaction with the right click and you can't access to the interface block example crafting table and other mods blocks and the remote universal lost all functions
 
if you try save, the game appear to not respond (Freeze) and you need close with brute force xD

Forge 14.22.0.2465  Minecraft 1.12.1
backpacks 1.12.1 - 3.3.2 ([this one ](https://mods.curse.com/mc-mods/minecraft/223957-backpacks#description))

and other mods xD

![backpackerror](https://user-images.githubusercontent.com/2113099/30009308-fee47c3e-90ec-11e7-86d6-1f332f234cd6.png)

**Comment by orbwoi** [comment]
Okay, I officially hate that mod. It is closed source and it is a core mod so it crashes every time I try to load it in the debugger.

I manged to fix it so it seem to be working properly with the remote in 0.9.2.

Please file bugs about any other mods which are important to be fixed first :)
